In [3]:
import pandas as pd
import numpy as np

df_ar_sa = pd.read_csv("arrets-de-travail-par-secteur-d-activite-naf-1-et-naf-5.csv", sep=";")
print("Loaded successfully! Shape:", df_ar_sa.shape)

Loaded successfully! Shape: (30240, 10)

In [4]:
df_ar_sa

,annee,code_NAF1,libelle_NAF1,NAF1,code_NAF5,libelle_NAF5,NAF5,risque,nb_jours_arret_travail,nb_jours_arret_travail_txt
0,2015,A,"Agriculture, sylviculture et pêche","A - Agriculture, sylviculture et pêche",0111Z,"Culture de céréales (à l'exception du riz), de...",0111Z - Culture de céréales (à l'exception du ...,Accidents de trajet,0.0,0
1,2015,A,"Agriculture, sylviculture et pêche","A - Agriculture, sylviculture et pêche",0111Z,"Culture de céréales (à l'exception du riz), de...",0111Z - Culture de céréales (à l'exception du ...,Accidents du travail,255.0,255
2,2015,A,"Agriculture, sylviculture et pêche","A - Agriculture, sylviculture et pêche",0111Z,"Culture de céréales (à l'exception du riz), de...",0111Z - Culture de céréales (à l'exception du ...,Maladies professionnelles,318.0,318
3,2015,A,"Agriculture, sylviculture et pêche","A - Agriculture, sylviculture et pêche",0111Z,"Culture de céréales (à l'exception du riz), de...",0111Z - Culture de céréales (à l'exception du ...,Tous risques confondus,573.0,573
4,2015,A,"Agriculture, sylviculture et pêche","A - Agriculture, sylviculture et pêche",0112Z,Culture du riz,0112Z - Culture du riz,Accidents de trajet,0.0,0
...,...,...,...,...,...,...,...,...,...,...
30235,2024,x,Valeur manquante,x - Valeur manquante,TOUS,Total Valeur manquante,Total Valeur manquante,Tous risques confondus,830262.0,830262
30236,2024,x,Valeur manquante,x - Valeur manquante,xxxxx,Valeur manquante,xxxxx - Valeur manquante,Accidents de trajet,43928.0,43928
30237,2024,x,Valeur manquante,x - Valeur manquante,xxxxx,Valeur manquante,xxxxx - Valeur manquante,Accidents du travail,106377.0,106377
30238,2024,x,Valeur manquante,x - Valeur manquante,xxxxx,Valeur manquante,xxxxx - Valeur manquante,Maladies professionnelles,679957.0,679957
30239,2024,x,Valeur manquante,x - Valeur manquante,xxxxx,Valeur manquante,xxxxx - Valeur manquante,Tous risques confondus,830262.0,830262

In [5]:
df_ar_sa.describe()

              annee  nb_jours_arret_travail
count  30240.000000            2.956500e+04
mean    2019.500000            1.332736e+05
std        2.872329            1.608434e+06
min     2015.000000            0.000000e+00
25%     2017.000000            1.377000e+03
50%     2019.500000            6.873000e+03
75%     2022.000000            3.021000e+04
max     2024.000000            7.888625e+07